# Transform class name to int
string_to_int = {'sink': 0,
                 'moustache' : 1,
                 'nose' : 2,
                 'skateboard' : 3,
                 'penguin': 4,
                 'peanut': 5,
                 'skull': 6,
                 'panda': 7,
                 'paintbrush': 8,
                 'nail': 9,
                 'apple': 10,
                 'rifle': 11,
                 'mug': 12,
                 'sailboat': 13,
                 'pineapple':14,
                 'spoon': 15,
                 'rabbit': 16,
                 'shovel': 17,
                 'screwdriver': 18,
                 'scorpion': 19,
                 'rhinoceros': 20,
                 'rollerskates': 21,
                 'pool': 22,
                 'octagon': 23,
                 'pillow':24,
                 'parrot':25,
                 'squiggle':26,
                 'mouth':27,
                 'empty':28,
                 'pencil':29,
                 'pear': 30
                 }

# Transform class int to string
int_to_string = {0: 'sink',
                 1: 'moustache',
                 2: 'nose',
                 3: 'skateboard',
                 4: 'penguin',
                 5: 'peanut',
                 6: 'skull',
                 7: 'panda',
                 8: 'paintbrush',
                 9: 'nail',
                 10: 'apple',
                 11: 'rifle',
                 12: 'mug',
                 13: 'sailboat',
                 14: 'pineapple',
                 15: 'spoon',
                 16: 'rabbit',
                 17: 'shovel',
                 18: 'screwdriver',
                 19: 'scorpion',
                 20: 'rhinoceros',
                 21: 'rollerskates',
                 22: 'pool',
                 23: 'octagon',
                 24: 'pillow',
                 25: 'parrot',
                 26: 'squiggle',
                 27: 'mouth',
                 28: 'empty',
                 29: 'pencil',
                 30: 'pear'
                 }

string_to_float = {'sink': 0.0,
                 'moustache' : 1.0,
                 'nose' : 2.0,
                 'skateboard' : 3.0,
                 'penguin': 4.0,
                 'peanut': 5.0,
                 'skull': 6.0,
                 'panda': 7.0,
                 'paintbrush': 8.0,
                 'nail': 9.0,
                 'apple': 10.0,
                 'rifle': 11.0,
                 'mug': 12.0,
                 'sailboat': 13.0,
                 'pineapple':14.0,
                 'spoon': 15.0,
                 'rabbit': 16.0,
                 'shovel': 17.0,
                 'screwdriver': 18.0,
                 'scorpion': 19.0,
                 'rhinoceros': 20.0,
                 'rollerskates': 21.0,
                 'pool': 22.0,
                 'octagon': 23.0,
                 'pillow':24.0,
                 'parrot':25.0,
                 'squiggle':26.0,
                 'mouth':27.0,
                 'empty':28.0,
                 'pencil':29.0,
                 'pear': 30.0
                 }

def label_to_int(e):
    return string_to_int[e]

def int_to_label(e):
    return int_to_string[e]

def label_to_float(e):
    return string_to_float[e]